load("simpledash.bzl", "jb_library", "simpledash_jsonnet_to_json")

jb_library(
    name = "grafonnet",
    jsonnetfile = "jsonnetfile.json",
    jsonnetfile_lock = "jsonnetfile.lock.json",
)

simpledash_jsonnet_to_json(
    name = "dashboards",
    srcs = [
        "dashboards/bb-scheduler.jsonnet",
        "dashboards/blobaccess.jsonnet",
        "dashboards/buildexecutor.jsonnet",
        "dashboards/centralized-storage.jsonnet",
        "dashboards/eviction-sets.jsonnet",
        "dashboards/fuse.jsonnet",
        "dashboards/grpc-clients.jsonnet",
        "dashboards/grpc-servers.jsonnet",
    ],
    imports = [":grafonnet"],
)
