load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("simpledash.bzl", "jb_library", "simpledash_jsonnet_to_json")

sh_binary(
    name = "run_jb",
    srcs = ["run_jb.sh"],
    # This tool is only used during build-time for rule jb_library.
    tags = ["manual"],
)

sh_binary(
    name = "run_jsonnet",
    srcs = ["run_jsonnet.sh"],
    # This tool is only used during build-time for rule simpledash_jsonnet_to_json.
    tags = ["manual"],
)

jb_library(
    name = "grafonnet",
    jsonnetfile = "jsonnetfile.json",
    jsonnetfile_lock = "jsonnetfile.lock.json",
)

simpledash_jsonnet_to_json(
    name = "dashboards",
    srcs = [
        "dashboards/bb-scheduler.jsonnet",
        "dashboards/blobaccess.jsonnet",
        "dashboards/buildexecutor.jsonnet",
        "dashboards/centralized-storage.jsonnet",
        "dashboards/eviction-sets.jsonnet",
        "dashboards/fuse.jsonnet",
        "dashboards/grpc-clients.jsonnet",
        "dashboards/grpc-servers.jsonnet",
    ],
    imports = [":grafonnet"],
)
