apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: buildbarn-config
  namespace: buildbarn
  files:
    - browser.jsonnet
    - common.libsonnet
    - frontend.jsonnet
    - runner-ubuntu22-04.jsonnet
    - scheduler.jsonnet
    - storage.jsonnet
    - worker-ubuntu22-04.jsonnet
