apiVersion: v1
data:
  scheduler.jsonnet: |
    local common = import 'common.libsonnet';
    {
      adminHttpListenAddress: common.httpListenAddress,
      clientGrpcServers: [{
        listenAddresses: [':8982'],
        authenticationPolicy: { allow: {} },
      }],
      workerGrpcServers: [{
        listenAddresses: [':8983'],
        authenticationPolicy: { allow: {} },
      }],
      defaultExecutionTimeout: '1800s',
      maximumExecutionTimeout: '3600s',
      executeAuthorizer: { allow: {} },
      contentAddressableStorage: common.blobstoreStorage.contentAddressableStorage,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      browserUrl: common.browserUrl,
    }
kind: ConfigMap
metadata:
  name: scheduler
  namespace: buildbarn