apiVersion: v1
data:
  scheduler.jsonnet: |
    local common = import 'common.libsonnet';

    {
      adminHttpListenAddress: ':7982',
      clientGrpcServers: [{
        listenAddresses: [':8982'],
        authenticationPolicy: { allow: {} },
      }],
      workerGrpcServers: [{
        listenAddresses: [':8983'],
        authenticationPolicy: { allow: {} },
      }],
      browserUrl: common.browserUrl,
      contentAddressableStorage: common.blobstore.contentAddressableStorage,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      executeAuthorizer: { allow: {} },
      actionRouter: {
        simple: {
          platformKeyExtractor: { actionAndCommand: {} },
          invocationKeyExtractors: [
            { correlatedInvocationsId: {} },
            { toolInvocationId: {} },
          ],
          initialSizeClassAnalyzer: {
            defaultExecutionTimeout: '1800s',
            maximumExecutionTimeout: '7200s',
          },
        },
      },
      platformQueueWithNoWorkersTimeout: '900s',
    }
kind: ConfigMap
metadata:
  name: scheduler
  namespace: buildbarn
