apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: event-service
  namespace: buildbarn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
      - image: buildbarn/bb-event-service:20190617T160116Z-3ab3681
        args:
        - /config/event-service.json
        name: event-service
        ports:
        - containerPort: 8983
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          name: event-service
        name: config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: event-service
  namespace: buildbarn
spec:
  ports:
  - port: 8983
    protocol: TCP
  selector:
    app: event-service
  type: LoadBalancer
