apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor
  namespace: buildbarn
  labels:
    release: prometheus-community
spec:
  selector:
    matchLabels:
      app: storage
  endpoints:
    - port: health-http